package com.tuprime.entities;


// default package
// Generated 27.Nis.2015 18:14:25 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.CascadeType;

/**
 * Diet generated by hbm2java
 */
@Entity
@Table(name = "diet", catalog = "sportclubsystem")
public class Diet implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	private Integer id;
	
	private Date timestamp;
	private String diet;

	@OneToMany(mappedBy = "diet")
	private Set<UserDiet> userDiet = new HashSet<UserDiet>();
	
	public Diet() {
	}

	public Diet(String diet) {
		this.diet = diet;
	}


	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.DATE)
	@Column(name = "timestamp", nullable = false, length = 10)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "diet", length = 1000)
	public String getDiet() {
		return this.diet;
	}

	public void setDiet(String diet) {
		this.diet = diet;
	}

	
	public Set<UserDiet> getUserDiet() {
		return userDiet;
	}

	public void setUserDiet(Set<UserDiet> userDiet) {
		this.userDiet = userDiet;
	}

	@Override
	public int hashCode() {
		return getId();
	}
	
	@Override
	public String toString() {
		return getDiet();
	}
	
	@Override
	public boolean equals(Object other) {
		if (this == other)
			return true;
		if (other == null || (this.getClass() != other.getClass())) {
			return false;
		}
		Diet guest = (Diet) other;
		return (this.id == guest.getId());
	}

}
