package com.tuprime.entities;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Muscle generated by hbm2java
 */
@Entity
@Table(name = "muscle", catalog = "sportclubsystem")
public class Muscle implements java.io.Serializable {

	private Integer id;
	private String muscle;

	public Muscle() {
	}

	public Muscle(String muscle) {
		this.muscle = muscle;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "muscle", nullable = false, length = 32)
	public String getMuscle() {
		return this.muscle;
	}

	public void setMuscle(String muscle) {
		this.muscle = muscle;
	}

}
