package com.tuprime.entities;


import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToOne;
import javax.persistence.CascadeType;
/**
 * PersonalDetails generated by hbm2java
 */
@Entity
@Table(name = "personal_details", catalog = "sportclubsystem")
public class PersonalDetails implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	private Integer id;
	
	private Date timestamp;
	private String weight;
	private String chest;
	private String waist;
	private String hips;
	private String biceps;

	
	@OneToMany(cascade=CascadeType.ALL)
	@JoinTable(name="user_pdetails",
	joinColumns={@JoinColumn(name="pdetails_id", referencedColumnName="id")},
	inverseJoinColumns={@JoinColumn(name="user_id", referencedColumnName="id")})
	private List<User> userList;
	
	
	public PersonalDetails() {
	}

	public PersonalDetails(String weight, String chest, String waist,
			String hips, String biceps) {
		this.weight = weight;
		this.chest = chest;
		this.waist = waist;
		this.hips = hips;
		this.biceps = biceps;
	}


	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.DATE)
	@Column(name = "timestamp", nullable = false, length = 10)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "weight", length = 20)
	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	@Column(name = "chest", length = 20)
	public String getChest() {
		return this.chest;
	}

	public void setChest(String chest) {
		this.chest = chest;
	}

	@Column(name = "waist", length = 20)
	public String getWaist() {
		return this.waist;
	}

	public void setWaist(String waist) {
		this.waist = waist;
	}

	@Column(name = "hips", length = 20)
	public String getHips() {
		return this.hips;
	}

	public void setHips(String hips) {
		this.hips = hips;
	}

	@Column(name = "biceps", length = 20)
	public String getBiceps() {
		return this.biceps;
	}

	public void setBiceps(String biceps) {
		this.biceps = biceps;
	}

	public List<User> getUserList() {
		return userList;
	}

	public void setUserList(List<User> userList) {
		this.userList = userList;
	}


}
