package com.tuprime.entities;

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.CascadeType;

/**
 * Workout generated by hbm2java
 */
@Entity
@Table(name = "workout", catalog = "sportclubsystem")
public class Workout implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	private Integer id;

	private Date timestamp;
	private String workoutProgram;
	@Column(name = "creator")
	private int creator;

	@OneToMany(mappedBy = "workout")
	private Set<UserWorkout> userWorkout = new HashSet<UserWorkout>();

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	@JoinTable(name = "workout_exercise", joinColumns = {
			@JoinColumn(name = "workout_id", referencedColumnName = "id") }, inverseJoinColumns = {
					@JoinColumn(name = "exercise_id", referencedColumnName = "id") })
	private Set<Exercise> exercises;

	public Workout() {
	}

	public Workout(String workoutProgram) {
		this.workoutProgram = workoutProgram;
	}

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.DATE)
	@Column(name = "timestamp", nullable = false, length = 10)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "workout_program", length = 1000)
	public String getWorkoutProgram() {
		return this.workoutProgram;
	}

	public void setWorkoutProgram(String workoutProgram) {
		this.workoutProgram = workoutProgram;
	}


	
	public Set<UserWorkout> getUserWorkout() {
		return userWorkout;
	}

	public void setUserWorkout(Set<UserWorkout> userWorkout) {
		this.userWorkout = userWorkout;
	}

	@Override
	public int hashCode() {
		return getId();
	}

	@Override
	public String toString() {
		return getWorkoutProgram();
	}
	
	@Override
	public boolean equals(Object other) {
		if (this == other)
			return true;
		if (other == null || (this.getClass() != other.getClass())) {
			return false;
		}
		Workout guest = (Workout) other;
		return (this.id == guest.getId());
	}

	public int getCreator() {
		return creator;
	}

	public void setCreator(int creator) {
		this.creator = creator;
	}

	public Set<Exercise> getExercises() {
		return exercises;
	}

	public void setExercises(Set<Exercise> exercises) {
		this.exercises = exercises;
	}

}
